# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24f0382b03dffa933c5d17135f049c46ea27caabb5adfa3078c6dfd011fdcb0c7674e3a7017858667fb0c5a9423244500927e541fbf7f5aecf3197ea14bbb3fd

test:
  secret_key_base: f5dd70387053c8c0962aeef24a005f12f317e135cbb8306d9aa24b4a4c749e84419c9fdd240433507644a928f63f0b547c59ee46fa329b800947fa1146dbc070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
